#2 concrete strength prediction with svm
EKU-Summer-2021/ml-assignment-saidsabri010 pull request #3
Opened 2021-07-14 18:24 UTC by saidsabri010

i read the dataset and train_test_split it,and created the svm class that get the score (SVR) and store the result in 
CSV file,for test,i checked if the output is an instance of pandas dataframe

2021-07-15 10:00 UTC, kadamQ requested changes

2021-07-15 10:00 UTC, kadamQ commented on src/svm.py
> +    fields = ['Score']
- The best score can change, so you should try to save the scores dynamically, not giving concrete values to the variables.
- Try to save the [best score](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) with the [best params ](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html)too. 
- For this use `best_score_` and `best_params_`.

2021-07-20 12:14 UTC, Benczus requested changes
Visualization of the regressor is important part of machine learning.
Please visualize the original data points with a scatter plot by taking a column of the dataset for the x and the target for the y axis.
Then use scatter plot to plot the same column with the predicted values as reference.
Since you have used standard scaler, please don't forget to use .inverse_transform(y_predict) before plotting

2021-07-20 12:14 UTC, Benczus commented on src/svm.py
> +        self.grid = GridSearchCV(SVR(), param_grid, refit=True, verbose=3)
Param Grid and Model can be taken as a parameter

2021-07-20 12:14 UTC, Benczus commented on src/svm.py
> +    def save(self):
visualization is missing

2021-07-21 13:15 UTC, merged